task: Implement function to return registered attendees for an event
mubarak23/chainevents-contracts pull request #31
Opened 2024-10-24 15:49 UTC by Abeeujah

closes #21 

This changes implements the following
- Function to return registered attendees for a given event (event_id)
- Tests to assert correctness

2024-10-25 16:31 UTC, mubarak23 requested changes
also pull from the main branch to resolve the merge conflict on the PR.

2024-10-25 16:31 UTC, mubarak23 commented on src/events/events.cairo
> +        fn registered_attendees(self: @ContractState, event_id: u256) -> u256 {
can you ensure the function caller is the event organizer

2024-10-25 16:31 UTC, mubarak23 commented on tests/test_contract.cairo
> +fn test_registered_attendees() {
prank that event owner is caller of this function

2024-10-25 16:31 UTC, mubarak23 commented on tests/test_contract.cairo
add a should panic test for case where the wrong owner call the function

2024-10-25 16:31 UTC, mubarak23 commented on Scarb.lock
remove this scarb.lock file

2024-10-28 06:18 UTC, mubarak23 commented
@Abeeujah any progress regarding this review requested

2024-10-28 10:41 UTC, Abeeujah commented on src/events/events.cairo
> +        fn registered_attendees(self: @ContractState, event_id: u256) -> u256 {
Done!

2024-10-28 10:41 UTC, Abeeujah commented on tests/test_contract.cairo
> +fn test_registered_attendees() {
Done!

2024-10-28 10:42 UTC, Abeeujah commented on tests/test_contract.cairo
Done!

2024-10-28 10:47 UTC, Abeeujah commented on Scarb.lock
Done!

2024-10-28 10:48 UTC, Abeeujah commented
All requested changes has been included @mubarak23 :rocket:

2024-10-28 10:58 UTC, merged